#ifndef __SNQ_PROGRAM_DEFINES_H__
#define __SNQ_PROGRAM_DEFINES_H__

/* SNQ trigger enable defines */
#define SNQ_TE_HT3_CORE_ERRRSP_STOMP_OR_DROP_INT		0
#define SNQ_TE_ECC_ERROR		1
#define SNQ_TE_ECC_FATAL		2
#define SNQ_TE_PCIE_CORE_LINK_STATUS_INT		3
#define SNQ_TE_PCIE_BRIDGE_PCIE_TO_HTOC_REGFILE_INFO		4
#define SNQ_TE_PCIE_BRIDGE_ERROR		5
#define SNQ_TE_PCIE_CORE_ERROR		6
#define SNQ_TE_TIMER_INTERRUPT		7
#define SNQ_TE_GPIO_IRQ		8
#define SNQ_TE_HTAX_BRIDGE_DISCARDED_INT		9
#define SNQ_TE_HTAX_ASSERTION		10
#define SNQ_TE_SMFU_MATCHING_STORE_EMPTY		11
#define SNQ_TE_SMFU_TIMEOUT		12
#define SNQ_TE_XBAR_INPORT		13
#define SNQ_TE_XBAR_OUTPORT		14
#define SNQ_TE_BARRIER_RELEASED		15
#define SNQ_TE_BARRIER_GLOBAL_INTERRUPT		16
#define SNQ_TE_LINK_PORT		17
#define SNQ_TE_LINK_MAC_LANE_ERROR		18
#define SNQ_TE_LINK_MAC_RETRAIN_ERROR		19
#define SNQ_TE_LINK_MAC_STATUS		20
#define SNQ_TE_BQ_ERROR		21
#define SNQ_TE_WCBUF_ERROR		22
#define SNQ_TE_VELO_RF_NOTI_INTERRUPT_HANDLER_NOTI_INTERRUPT_VEC		23
#define SNQ_TE_VELO_ERROR		24
#define SNQ_TE_RMA_RF_NOTI_INTERRUPT_HANDLER_NOTI_INTERRUPT_VEC		25
#define SNQ_TE_RMA_HISTORY_DUMP		26
#define SNQ_TE_RMA_ERROR		27
#define SNQ_TE_NW_STATE		28
#define SNQ_TE_TE_29		29
#define SNQ_TE_TE_30		30
#define SNQ_TE_TE_31		31

#define SNQ_TRIG_NUM_MAX 0x20
#define SNQ_TRIG_VAL(te,entry) (te + entry*256)
#define SNQ_TE(val) (val & 0xff)
#define SNQ_ENTRY(val) (val / 256)


#endif // __SNQ_PROGRAM_DEFINES_H__
