#!/bin/bash

# (C) 2012 by EXTOLL GmbH

#########################################################
#                                                       #
# Simple Script to configure an EXTOLL R2 Network       #
#                                                       #
# This script uses ssh to log into a list of nodes      #
# and loads the kernel drivers using extoll_load.sh     #
# on each node.                                         #
# Then the routing table is set as specified below      #
#                                                       #
# To use this script, you need to edit the following    #
# variables below:                                      #
#                                                       #
# * path: this should point to the path of the sysfs    #
#    entries of EXTOLL on the nodes to be configured    #
# * num_nodes: set this variable to the number of nodes #
# * node_base_name: set this to the base host name of   #
#   the nodes to be configured. The hostname for ssh    #
#   will then be generated by concatenating a number    #
#   to this base name                                   #
# * routing: the routing table of the network.          #
#   This quadratic table consists of one entry for each #
#   destination on each host. See also below            #
#########################################################

#determin where the script is called from and that dir to ba_mexs
DIR="`dirname \"$0\"`"		# relative
DIR="`( cd \"$DIR\" && pwd )`"	# absolute and normalized
if [ -z "$DIR" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1 # fail
fi

#source to get path information                                                        
source ../extoll_env.bash
#remember sysfs path
path=$EXTOLL_R2_SYSFS

#path=/sys/bus/pci/devices/0000\:20\:06.0/extoll_rf

#set size of the network and basename of nodes -> needs to be adjusted for the cluster
num_nodes=4
node_base_num=8
node_base_name=peac

#completely initialize one node
#Parameter: $1: node num
#parameter: $2 .. ${num_nodes}: links to reach the corresponding node
init_node()
{
 current_node=$1
 #echo "Node to be configured is $current_node, routing links is $routing_links" 
 echo  "Init node with ${node[$1]}"
 ssh ${node[$1]} "$EXTOLL_R2_HOME/sbin/extoll_unload.sh"
 ssh ${node[$1]} "$EXTOLL_R2_HOME/sbin/extoll_load.sh"
 ssh ${node[$1]} 'for cpu in /sys/devices/system/cpu/cpu? ; do echo performance> ${cpu}/cpufreq/scaling_governor ; done'
 ssh ${node[$1]} 'sysctl -w net.ipv6.conf.all.disable_ipv6=1'
 ssh ${node[$1]} "cat ${path}/extoll_rf_nw_lp_top_rf_lp0_lp_in"
 ssh ${node[$1]} "echo 0x180000000000003 > ${path}/extoll_rf_nw_lp_top_rf_lp0_lp_in"
 ssh ${node[$1]} "cat ${path}/extoll_rf_nw_lp_top_rf_lp1_lp_in"
 ssh ${node[$1]} "echo 0x180000000000003 > ${path}/extoll_rf_nw_lp_top_rf_lp1_lp_in"
 ssh ${node[$1]} "cat ${path}/extoll_rf_nw_lp_top_rf_lp2_lp_in"
 ssh ${node[$1]} "echo 0x180000000000003 > ${path}/extoll_rf_nw_lp_top_rf_lp2_lp_in"
 ssh ${node[$1]} "cat ${path}/extoll_rf_nw_lp_top_rf_lp3_lp_in"
 ssh ${node[$1]} "echo 0x180000000000003 > ${path}/extoll_rf_nw_lp_top_rf_lp3_lp_in"
 return 0
}

echo "EXTOLL MEXS Network Setup Script"
echo "(C) 2012 by EXTOLL GmbH"
echo -n
# generate node name array
for ((i=$node_base_num, j=0;i < $node_base_num+$num_nodes ; i++, j++))
do
 #echo $j $i
 if (($i < 10)) ; then num=0$i ; else num=$i ; fi
 #echo $j $i
 echo "Found node $node_base_name$num"
 node[$j]=$node_base_name$num
done

for ((n=0;n < $num_nodes ; n++))
do
 init_node $n
done

echo "Calling MEXS to setup routing"
ba_mexs -tf $DIR/files/extoll_rf.anot.xml -tf $DIR/files/routing/grid_2x2.xml

echo "Seting-up EXN ETH Interfaces..."
for ((n=0;n < $num_nodes ; n++))
do
 ssh ${node[$n]} "insmod $EXTOLL_R2_HOME/sbin/exn.ko"
 ssh ${node[$n]} "ifconfig exn0 10.2.0.${n} up"
done

echo "Setting up of EXTOLL network with $num_nodes nodes done."
